(() => {
  'use strict';
  const DB_NAME='sweater-local-studio'; const DB_VERSION=1;
  const tool=decodeURIComponent(location.pathname.split('/').pop()||'index.html');
  const toolNames={'index.html':'لوحة الأدوات','framing-tool.html':'تركيب الإطارات','coupon-tool.html':'صانع الكوبونات','Quotation Generator.html':'عروض الأسعار','n_icons.html':'استوديو التصميم','logo-framer-tool.html':'قوالب الشراكات','qr-generator.html':'صانع QR Code','document-logo-tool.html':'ختم الملفات بالشعار','package-card-tool.html':'كروت الباقات'};
  const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const request=p=>new Promise((resolve,reject)=>{p.onsuccess=()=>resolve(p.result);p.onerror=()=>reject(p.error)});
  const openDB=()=>new Promise((resolve,reject)=>{const q=indexedDB.open(DB_NAME,DB_VERSION);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains('projects')){const s=d.createObjectStore('projects',{keyPath:'id'});s.createIndex('tool','tool');s.createIndex('updatedAt','updatedAt')}if(!d.objectStoreNames.contains('assets')){const s=d.createObjectStore('assets',{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('type','type')}if(!d.objectStoreNames.contains('activity')){const s=d.createObjectStore('activity',{keyPath:'id'});s.createIndex('createdAt','createdAt')}};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});
  const tx=async(store,mode,fn)=>{const db=await openDB();const t=db.transaction(store,mode);const result=await fn(t.objectStore(store));await new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close();return result};
  const all=store=>tx(store,'readonly',s=>request(s.getAll()));
  const put=(store,value)=>tx(store,'readwrite',s=>request(s.put(value)));
  const del=(store,id)=>tx(store,'readwrite',s=>request(s.delete(id)));
  const log=async(message,icon='fa-bolt')=>put('activity',{id:uid(),message,icon,createdAt:new Date().toISOString()});
  const projectKeys={
    'framing-tool.html':[],
    'coupon-tool.html':['sweaterCouponAutosaveV2'],
    'Quotation Generator.html':['sweaterQuotationAutosaveV2'],
    'n_icons.html':['sweaterDesignAutosaveV3','sweater-design-autosave-v3'],
    'qr-generator.html':['sweaterQrHistoryV1'],
    'document-logo-tool.html':[],
    'package-card-tool.html':[],
    'logo-framer-tool.html':[]
  };
  const localSnapshot=()=>{const data={};const allowed=new Set(['swDark',`sw:draft:${tool}`,...(projectKeys[tool]||[])]);for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&allowed.has(k))data[k]=localStorage.getItem(k)}return data};
  const domSnapshot=()=>({fields:[...document.querySelectorAll('input[id]:not([type=file]):not([type=password]),textarea[id],select[id]')].map(e=>({id:e.id,value:e.value,checked:e.checked,type:e.type})),editable:[...document.querySelectorAll('[contenteditable=true][data-field]')].map(e=>({field:e.dataset.field,index:[...document.querySelectorAll(`[contenteditable=true][data-field="${e.dataset.field}"]`)].indexOf(e),html:e.innerHTML}))});
  const applyDOM=s=>{s?.fields?.forEach(x=>{const e=document.getElementById(x.id);if(!e)return;if(x.type==='checkbox'||x.type==='radio')e.checked=x.checked;else e.value=x.value;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))});s?.editable?.forEach(x=>{const e=document.querySelectorAll(`[contenteditable=true][data-field="${x.field}"]`)[x.index];if(e){e.innerHTML=x.html;e.dispatchEvent(new Event('input',{bubbles:true}))}})};
  const pending=localStorage.getItem('sw:pendingRestore');if(pending){try{const p=JSON.parse(pending);Object.entries(p.local||{}).forEach(([k,v])=>localStorage.setItem(k,v));sessionStorage.setItem('sw:pendingDom',JSON.stringify(p.dom||{}))}catch(_){}localStorage.removeItem('sw:pendingRestore');location.reload();return}
  const pendingDom=sessionStorage.getItem('sw:pendingDom');if(pendingDom){sessionStorage.removeItem('sw:pendingDom');try{setTimeout(()=>applyDOM(JSON.parse(pendingDom)),300)}catch(_){}}

  const shell=document.createElement('div');shell.className='ls-shell';shell.innerHTML=`<aside class="ls-panel"><header class="ls-head"><div class="ls-head-row"><div class="ls-brand"><i class="fa-solid fa-layer-group"></i></div><div class="ls-title"><strong>مساحة SWEATER المحلية</strong><span>مشاريع وأصول محفوظة بالكامل على جهازك</span></div><button class="ls-close" aria-label="إغلاق"><i class="fa-solid fa-xmark"></i></button></div><div class="ls-tabs"><button class="ls-tab active" data-view="projects">المشاريع</button><button class="ls-tab" data-view="assets">مكتبة الأصول</button><button class="ls-tab" data-view="overview">النشاط</button></div></header><main class="ls-body"><section class="ls-view active" data-view="projects"></section><section class="ls-view" data-view="assets"></section><section class="ls-view" data-view="overview"></section></main><input class="ls-hidden-input" id="lsAssetInput" type="file" accept="image/*,.svg" multiple><input class="ls-hidden-input" id="lsBundleInput" type="file" accept=".sweater,.json"></aside>`;document.body.appendChild(shell);
  const launcher=document.createElement('button');launcher.className='ls-launcher';launcher.title='المشاريع والأصول المحلية';launcher.setAttribute('aria-label','فتح المشاريع المحلية');launcher.innerHTML='<i class="fa-solid fa-hard-drive"></i><span>المشاريع</span><span class="ls-launcher-count">0</span>';const pageHeader=document.querySelector('header,.top-bar');const studioTarget=pageHeader?.querySelector(':scope > .controls-container, :scope > .actions, :scope > .top-actions, :scope > .head-actions, :scope > .head-side, :scope > .header-actions')||pageHeader?.lastElementChild;if(studioTarget){launcher.classList.add('in-header');studioTarget.prepend(launcher)}else document.body.appendChild(launcher);
  const body=shell.querySelector('.ls-body');
  const fmt=d=>new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d));
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  async function saveProject(){const name=prompt('اسم المشروع:',`${toolNames[tool]||'مشروع'} — ${new Date().toLocaleDateString('ar-SA')}`);if(!name)return;const existing=(await all('projects')).filter(p=>p.tool===tool&&p.name===name)[0];const now=new Date().toISOString();await put('projects',{id:existing?.id||uid(),name,tool,toolName:toolNames[tool]||tool,createdAt:existing?.createdAt||now,updatedAt:now,local:localSnapshot(),dom:domSnapshot(),versions:[...(existing?.versions||[]).slice(-9),...(existing?[{at:existing.updatedAt,local:existing.local,dom:existing.dom}]:[])]});await log(`تم حفظ مشروع «${name}»`,'fa-floppy-disk');await render();}
  async function loadProject(id){const p=await tx('projects','readonly',s=>request(s.get(id)));if(!p)return;if(p.tool!==tool){localStorage.setItem('sw:pendingRestore',JSON.stringify({local:p.local,dom:p.dom}));location.href=`./${p.tool}`;return}Object.entries(p.local||{}).forEach(([k,v])=>localStorage.setItem(k,v));sessionStorage.setItem('sw:pendingDom',JSON.stringify(p.dom||{}));await log(`تم فتح مشروع «${p.name}»`,'fa-folder-open');location.reload()}
  async function cloneProject(id){const p=await tx('projects','readonly',s=>request(s.get(id)));if(!p)return;const now=new Date().toISOString();await put('projects',{...p,id:uid(),name:`نسخة من ${p.name}`,createdAt:now,updatedAt:now,versions:[]});await render()}
  async function exportProject(id){const p=await tx('projects','readonly',s=>request(s.get(id)));const blob=new Blob([JSON.stringify({format:'sweater-project',version:3,project:p},null,2)],{type:'application/json'});download(blob,`${p.name.replace(/[^\p{L}\p{N}-]+/gu,'-')}.sweater`)}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  const fileData=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)});
  async function addAssets(files){const existing=await all('assets');let added=0;for(const file of files){if(file.size>25*1024*1024||existing.some(a=>a.name===file.name&&a.size===file.size&&a.type===file.type))continue;await put('assets',{id:uid(),name:file.name,type:file.type,size:file.size,blob:file,createdAt:new Date().toISOString()});added++}if(added)await log(`تمت إضافة ${added} أصل إلى المكتبة`,'fa-images');await render()}
  async function useAsset(id){const a=await tx('assets','readonly',s=>request(s.get(id)));const input=[...document.querySelectorAll('input[type=file]')].find(x=>/image|svg|png|jpg|jpeg|webp/.test(x.accept));if(!input){download(a.blob,a.name);return}const dt=new DataTransfer();dt.items.add(new File([a.blob],a.name,{type:a.type}));input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));shell.classList.remove('open');await log(`تم استخدام الأصل «${a.name}»`,'fa-wand-magic-sparkles')}
  async function importBundle(file){try{const j=JSON.parse(await file.text());if(j.format==='sweater-project'&&j.project){await put('projects',{...j.project,id:j.project.id||uid(),updatedAt:new Date().toISOString()});await log(`تم استيراد مشروع «${j.project.name}»`,'fa-file-import')}await render()}catch(_){alert('تعذر قراءة حزمة المشروع.') }}
  async function render(){const [projects,assets,activity]=await Promise.all([all('projects'),all('assets'),all('activity')]);launcher.querySelector('.ls-launcher-count').textContent=projects.length;projects.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));assets.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));activity.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
    shell.querySelector('[data-view=projects].ls-view').innerHTML=`<div class="ls-section-head"><div><h3>المشاريع المحلية</h3><p>لقطات مستقلة مع سجل نسخ لكل مشروع</p></div><div class="ls-actions"><button class="ls-btn" id="lsImport"><i class="fa-solid fa-file-import"></i>استيراد</button><button class="ls-btn primary" id="lsSave"><i class="fa-solid fa-plus"></i>حفظ الحالي</button></div></div><div class="ls-grid">${projects.length?projects.map(p=>`<article class="ls-card"><div class="ls-card-icon"><i class="fa-solid fa-folder"></i></div><div class="ls-card-main"><strong>${esc(p.name)}</strong><span>${esc(p.toolName)} · ${fmt(p.updatedAt)} · ${(p.versions||[]).length} نسخ</span></div><div class="ls-card-tools"><button class="ls-icon-btn" data-load="${p.id}" title="فتح"><i class="fa-solid fa-arrow-up-right-from-square"></i></button><button class="ls-icon-btn" data-clone="${p.id}" title="إنشاء نسخة"><i class="fa-solid fa-copy"></i></button><button class="ls-icon-btn" data-export="${p.id}" title="تصدير حزمة"><i class="fa-solid fa-box-archive"></i></button><button class="ls-icon-btn" data-del-project="${p.id}" title="حذف"><i class="fa-solid fa-trash"></i></button></div></article>`).join(''):`<div class="ls-empty"><i class="fa-regular fa-folder-open"></i><strong>لا توجد مشاريع بعد</strong><p>احفظ حالة أي أداة وستتمكن من الرجوع إليها أو إنشاء نسخة منها في أي وقت.</p></div>`}</div>`;
    const urls=[];shell.querySelector('[data-view=assets].ls-view').innerHTML=`<div class="ls-section-head"><div><h3>مكتبة الأصول</h3><p>صور وشعارات محفوظة محليًا لإعادة الاستخدام</p></div><button class="ls-btn primary" id="lsAddAssets"><i class="fa-solid fa-plus"></i>إضافة أصول</button></div><label class="ls-drop" for="lsAssetInput"><i class="fa-solid fa-cloud-arrow-up"></i> اختر صورًا أو شعارات لإضافتها للمكتبة</label><div class="ls-grid" style="margin-top:12px">${assets.length?assets.map(a=>{const url=URL.createObjectURL(a.blob);urls.push(url);return`<article class="ls-card"><div class="ls-thumb"><img src="${url}" alt=""></div><div class="ls-card-main"><strong>${esc(a.name)}</strong><span>${(a.size/1024).toFixed(0)} KB · ${fmt(a.createdAt)}</span></div><div class="ls-card-tools"><button class="ls-icon-btn" data-use="${a.id}" title="استخدام"><i class="fa-solid fa-wand-magic-sparkles"></i></button><button class="ls-icon-btn" data-download-asset="${a.id}" title="تنزيل"><i class="fa-solid fa-download"></i></button><button class="ls-icon-btn" data-del-asset="${a.id}" title="حذف"><i class="fa-solid fa-trash"></i></button></div></article>`}).join(''):`<div class="ls-empty"><i class="fa-regular fa-images"></i><strong>المكتبة فارغة</strong><p>أي صورة ترفعها للأدوات ستضاف تلقائيًا هنا، ويمكنك تنظيمها وإعادة استخدامها.</p></div>`}</div>`;
    shell.querySelector('[data-view=overview].ls-view').innerHTML=`<div class="ls-metric-grid"><div class="ls-metric"><strong>${projects.length}</strong><span>مشاريع محفوظة</span></div><div class="ls-metric"><strong>${assets.length}</strong><span>أصول محلية</span></div><div class="ls-metric"><strong>${projects.reduce((n,p)=>n+(p.versions||[]).length,0)}</strong><span>نسخ تاريخية</span></div></div><div class="ls-section-head"><div><h3>آخر النشاطات</h3><p>سجل محلي لا يغادر جهازك</p></div></div>${activity.slice(0,30).map(a=>`<div class="ls-activity"><i class="fa-solid ${a.icon}"></i><div>${esc(a.message)}<time>${fmt(a.createdAt)}</time></div></div>`).join('')||'<div class="ls-empty">لا توجد نشاطات بعد</div>'}`;
    shell.querySelector('#lsSave')?.addEventListener('click',saveProject);shell.querySelector('#lsImport')?.addEventListener('click',()=>shell.querySelector('#lsBundleInput').click());shell.querySelector('#lsAddAssets')?.addEventListener('click',()=>shell.querySelector('#lsAssetInput').click());
    body.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadProject(b.dataset.load));body.querySelectorAll('[data-clone]').forEach(b=>b.onclick=()=>cloneProject(b.dataset.clone));body.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportProject(b.dataset.export));body.querySelectorAll('[data-del-project]').forEach(b=>b.onclick=async()=>{if(confirm('حذف هذا المشروع؟')){await del('projects',b.dataset.delProject);await render()}});body.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>useAsset(b.dataset.use));body.querySelectorAll('[data-download-asset]').forEach(b=>b.onclick=async()=>{const a=await tx('assets','readonly',s=>request(s.get(b.dataset.downloadAsset)));download(a.blob,a.name)});body.querySelectorAll('[data-del-asset]').forEach(b=>b.onclick=async()=>{if(confirm('حذف هذا الأصل؟')){await del('assets',b.dataset.delAsset);await render()}});setTimeout(()=>urls.forEach(URL.revokeObjectURL),60000)
  }
  launcher.onclick=async()=>{shell.classList.add('open');await render()};shell.querySelector('.ls-close').onclick=()=>shell.classList.remove('open');shell.onclick=e=>{if(e.target===shell)shell.classList.remove('open')};shell.querySelectorAll('.ls-tab').forEach(t=>t.onclick=()=>{shell.querySelectorAll('.ls-tab,.ls-view').forEach(x=>x.classList.remove('active'));t.classList.add('active');shell.querySelector(`.ls-view[data-view="${t.dataset.view}"]`).classList.add('active')});shell.querySelector('#lsAssetInput').onchange=e=>addAssets([...e.target.files]);shell.querySelector('#lsBundleInput').onchange=e=>e.target.files[0]&&importBundle(e.target.files[0]);
  document.addEventListener('change',e=>{const input=e.target;if(!(input instanceof HTMLInputElement)||input.type!=='file'||!input.files?.length||input.closest('.ls-shell'))return;addAssets([...input.files].filter(f=>f.type.startsWith('image/')||f.type==='image/svg+xml'))},true);
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject()}if(e.key==='Escape'&&shell.classList.contains('open'))shell.classList.remove('open')});
  all('projects').then(p=>launcher.querySelector('.ls-launcher-count').textContent=p.length).catch(()=>{});
})();
