create table if not exists public.writer_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'محادثة جديدة',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.writer_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.writer_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.writer_settings (
  id text primary key default 'default' check (id = 'default'),
  system_instructions text not null default 'أنت كاتب محتوى محترف لعلامة سويتر. اكتب بالعربية الواضحة، واطلب التفاصيل الناقصة عند الحاجة، وقدّم محتوى جاهزاً للاستخدام.',
  updated_at timestamptz not null default now()
);

insert into public.writer_settings (id) values ('default') on conflict (id) do nothing;

alter table public.writer_conversations enable row level security;
alter table public.writer_messages enable row level security;
alter table public.writer_settings enable row level security;

create policy "users_manage_own_writer_conversations"
on public.writer_conversations for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users_manage_own_writer_messages"
on public.writer_messages for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "authenticated_read_writer_settings"
on public.writer_settings for select to authenticated
using (true);

grant select, insert, update, delete on public.writer_conversations to authenticated;
grant select, insert, update, delete on public.writer_messages to authenticated;
grant usage, select on sequence public.writer_messages_id_seq to authenticated;
grant select on public.writer_settings to authenticated;

create index if not exists writer_conversations_user_updated_idx
on public.writer_conversations (user_id, updated_at desc);

create index if not exists writer_messages_conversation_created_idx
on public.writer_messages (conversation_id, created_at);
